### 게시글 생성
POST /localhost:8080/posts
Content-Type: application/json

{
    "title": "title",
    "content": "content",
    "createdBy": "createdBy",
    "tags": [
        "tag1",
        "tag2"
    ]
}

### 게시글 수정
PUT /localhost:8080/posts/5
Content-Type: application/json

{
    "title": "title",
    "content": "content",
    "updatedBy": "createdBy",
    "tags": [
        "tag1",
        "tag2"
    ]
}

### 게시글 삭제
DELETE /localhost:8080/posts/1?createdBy=hk
Content-Type: application/json

### 게시글 상세조회
GET /localhost:8080/posts/5

### 게시글 목록 조회
GET /localhost:8080/posts?page=0&size=5&tag=kotlin
